### ISSUE TITLE
Mapillary/OpenStreetCam integration

### ISSUE THREAD

**Issue by systemed** [mmd-osm/osm-maxheight-map#1]
This is brilliant - can't believe I haven't seen it before.

Have you thought about integrating a Mapillary and/or OpenStreetCam viewer into the page? It strikes me that a lot of these restrictions could be trivially mapped from such images. (Obviously it may be possible to view such imagery once you've launched the editor, but it would be really convenient to have it built in to the maxheight map.)

**Comment by mmd-osm** [comment]
There used to be some prototype level Mapillary integration, though it doesn't seem to work any longer, see: https://forum.openstreetmap.org/viewtopic.php?pid=504332#p504332

I'll need to have a look at what's going wrong here.

**Comment by mmd-osm** [comment]
It still seems to be working: http://maxheight.bplaced.net/overpass/map.html?mapillary=1&zoom=18&lat=50.45439&lon=7.66754&layers=B0000000FFFFFFFFFFTFT&label=F&style=line&opacity=70

on one of the many orange dots, the following image appears with a clearly legible clearance of 3,4m - https://d1cuyjsrcm0gby.cloudfront.net/6NPmTNqqJHW5fTikp3iBvw/thumb-1024.jpg

**Comment by mmd-osm** [comment]
Unfortunately, folks over at Mapillary completely changed their API, breaking this tiny little prototype. As I don't have much motivation to figure out how their new API works (only to find out that they'll break it again in the near future), I'm just leaving this thing as is it now.
